# Generated by Django 3.0.6 on 2020-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200702_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='facade.jpg', upload_to='banner_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pics/roboraptor.jpg', upload_to='profile_pics'),
        ),
    ]
