# Generated by Django 3.0.6 on 2020-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentions', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('name', models.CharField(max_length=500)),
                ('initial_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
